[ENG-850] Trustedform Refactor
TheDMSGroup/mautic-enhancer pull request #86
Opened 2019-03-28 20:28 UTC by heathdutton

2019-03-28 20:47 UTC, cykonetic requested changes
I believe getEnhancerFieldArray is an abstract method that needs to be defined, even if it returns an empty array

2019-03-29 13:58 UTC, cykonetic approved these changes
Looks good. I see where the methods moved to.

2019-03-29 20:18 UTC, scottshipman reviewed
see comment about docbloc.

2019-03-29 20:18 UTC, scottshipman commented on Integration/TrustedFormIntegration.php
> +     * (will call $this->authenticationTypeCallback).
update docbloc to say it returns basic?

2019-03-29 20:26 UTC, scottshipman approved these changes

2019-03-29 20:26 UTC, merged